plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':ewm-stats-service:statistics-dto')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.xmlunit:xmlunit-core'
    implementation 'org.mapstruct:mapstruct:1.5.3.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
}

springBoot {
    mainClass = 'ru.practicum.StatsServer'
}

tasks.named('bootJar') {
    archiveFileName = 'stats-server.jar'
}

tasks.named('jar') {
    enabled = false
}
