DROP TABLE IF EXISTS endpoints_hits;

CREATE TABLE IF NOT EXISTS endpoints_hits
(
    endpoint_hit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_hit_app       VARCHAR(255),
    endpoint_hit_uri       VARCHAR(255),
    endpoint_hit_ip        VARCHAR(255),
    endpoint_hit_timestamp TIMESTAMP WITHOUT TIME ZONE
);